wafflestudio/22-5-team7-server

- src/main/resources/application.yaml
- 이슈 번호: #6
- [√ ] 기타: cors 지움
---
- [v] 코드가 잘 빌드됨
- [ v] Linter
- [ v] 모든 테스트 통과
- [ v] kanban update
> :fire: removed cors() part

- src/main/kotlin/com/toyProject7/karrot/security/SecurityConstants.kt
- src/main/kotlin/com/toyProject7/karrot/user/controller/UserController.kt
- src/main/resources/application.yaml
- 이슈 번호:
- [ √] 백엔드: Spring Boot 관련 기능 추가/수정
---
- 소셜 로그인을 위한 /login/oauth2/** 권한 부여
- [√ ] 코드가 잘 빌드됨
- [ √] Linter
- [ √] 모든 테스트 통과
- [ √] kanban update
> Feat/social login PUBLIC_PATH에 /login/oauth2/** 추가

- src/main/kotlin/com/toyProject7/karrot/AwsS3Config.kt
- src/main/kotlin/com/toyProject7/karrot/article/ArticleException.kt
- src/main/kotlin/com/toyProject7/karrot/article/service/ArticleService.kt
- src/main/kotlin/com/toyProject7/karrot/security/SecurityConstants.kt
- src/main/kotlin/com/toyProject7/karrot/user/controller/User.kt
- src/main/kotlin/com/toyProject7/karrot/user/controller/UserController.kt
…nged
- 이슈 번호: #13
---
- <간략히 추가/변경된 기능/코드 내용을 작성하세요>
- 예) 상품 추가 API 구현
- 예) 회원가입 UI 수정
1. **작업 A**: <작업 A의 상세 설명>
2. **작업 B**: <작업 B의 상세 설명>
3. **작업 C**: <작업 C의 상세 설명>
---
---
- <머지 전 리뷰 시 확인해야 할 특이사항을 작성하세요>
- 예) 특정 기능이 로컬에서만 동작하니 환경 설정 확인 필요
- 예) DB Schema 변경으로 마이그레이션 필수
---
- <참고 링크나 문서를 입력하세요>
- 예) [Spring Boot Documentation](https://spring.io/projects/spring-boot)
- 예) [React 공식 문서](https://reactjs.org/)
> Image 관련 디버깅 코드 추가, User.kt & AwsS3Config.kt 수정됨

- src/main/kotlin/com/toyProject7/karrot/article/controller/Article.kt
- src/main/kotlin/com/toyProject7/karrot/article/controller/Item.kt
- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleEntity.kt
- src/main/kotlin/com/toyProject7/karrot/article/service/ArticleService.kt
- src/main/kotlin/com/toyProject7/karrot/image/persistence/ImageUrlEntity.kt
- src/main/kotlin/com/toyProject7/karrot/image/persistence/ImageUrlRepository.kt
- src/main/kotlin/com/toyProject7/karrot/image/service/ImageService.kt
- src/main/kotlin/com/toyProject7/karrot/user/UserAccessTokenUtil.kt
- 이슈 번호: #14 
---
- ImageUrlEntity/ImageRepository 생성
- ArticleEntity의 url 관련 column들을 List<String> -> MutableList<ImageUrlEntity>로 바꿈
- Article과 Item은 자료형 변화 x
1. ImageUrlEntity는 id(Long), article(ArticleEntity), url(String)으로 구성. 
2. 기존 ArticleService/ImageService와 골조는 동일. List<String> -> MutableList<ImageUrlEntity>로 바뀌면서 생기는 불가피한 수정만 적용. 
---
---
> 🔧 Fix image bug / make imageUrl repository

- .github/workflows/ci-cd.yml
- src/main/kotlin/com/toyProject7/karrot/KarrotApplication.kt
- src/main/resources/application.yaml
- 이슈 번호: # 18
---
- 소셜 로그인 git secrets passing 코드 추가
1. 소셜 로그인 git secrets passing 코드 추가
---
- [√] Linter
- [√] 모든 테스트 통과
- [√] kanban update
> 소셜 로그인 git secrets passing 디버깅

- src/main/kotlin/com/toyProject7/karrot/KarrotApplication.kt
- 이슈 번호: #18 
---
- kakao_client_id renamed to kakao_cli_id
1. kakao_client_id renamed to kakao_cli_id
---
- [√] Linter
- [√] 모든 테스트 통과
- [√] kanban update
> :bug: kakao_client_id renamed to kakao_cli_id

- src/main/kotlin/com/toyProject7/karrot/SecurityConfig.kt
- src/main/resources/application.yaml
- 이슈 번호: #18 
---
- 디버깅 로그 설정
- redirectUri explicit 정의
> 소셜 로그인 디버깅

- src/main/kotlin/com/toyProject7/karrot/KarrotApplication.kt
- src/main/resources/application.yaml
- 이슈 번호: #20 
---
- google secret and id
> :bug: google secret and id

- src/main/kotlin/com/toyProject7/karrot/image/service/ImageService.kt
- 이슈 번호: #15 
---
- ImageService get->put 수정
1. ImageService get->put 수정
---
> 🔧 Fix getrequest to putrequest

- src/main/kotlin/com/toyProject7/karrot/KarrotApplication.kt
- src/main/resources/application.yaml
- 이슈 번호: #20 
---
- 소셜 로그인 디버깅 org.springframework.web: DEBUG 추가
> 소셜 로그인 디버깅 org.springframework.web: DEBUG 추가

- src/main/kotlin/com/toyProject7/karrot/socialLogin/controller/SocialLoginController.kt
- 이슈 번호: #20 
---
- 구글 소셜 로그인 secret과 redirect_uri이 잘 보내지는지 확인하기 위해 @GetMapping 추가
> :bug: added debuggin code

- .github/workflows/ci-cd.yml
- src/main/resources/application.yaml
- 이슈 번호: #20 
---
- client_secret과 client_id 변수명 변경
1. 헷갈림을 방지하기 위해 github secrets 변수명으로 통일
> :pencil: united client id and secret variable name

- .github/workflows/ci-cd.yml
- 이슈 번호: #29 
---
- CD 부분에서 변수명 변경 누락, 여기서 다시 바꿈
> 소셜로그인 디버깅 secrets 변수명 문제

- src/main/kotlin/com/toyProject7/karrot/article/controller/Article.kt
- src/main/kotlin/com/toyProject7/karrot/article/controller/ArticleController.kt
- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleLikesRepository.kt
- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleRepository.kt
- src/main/kotlin/com/toyProject7/karrot/article/service/ArticleService.kt
- src/main/kotlin/com/toyProject7/karrot/comment/CommentException.kt
- src/main/kotlin/com/toyProject7/karrot/comment/controller/CommentController.kt
- src/main/kotlin/com/toyProject7/karrot/comment/service/CommentService.kt
- src/main/kotlin/com/toyProject7/karrot/feed/service/FeedService.kt
- 이슈 번호: #31
---
- 댓글 작성(postComment)
- 댓글 수정(editComment)
- 사용자의 좋아요 여부 반환(Article.kt에 isLiked: Boolean 추가)
1. CommentController & CommentService: postComment, editComment 함수 추가
2. Article.kt에 isLiked 추가: 만약 사용자가 클릭한 게시물에 사용자가 좋아요를 눌렀던 상태이면 isLiked = true로 반환해줌. 
---
---
- 없음.
---
- 없음.
> 댓글 작성, 댓글 수정, 사용자의 좋아요 여부 반환

- src/main/resources/application.yaml
- 이슈 번호: #20 
---
- 
1.  현재 redirect_uri 이 https가 아닌 http로 redirect하기 때문에 실제 주소로 변경
---
- [√] Linter
- [√] 모든 테스트 통과
- [√] kanban update
> 소셜로그인 redirect_uri 동적이 아닌 실제 주소로 변경

- src/main/kotlin/com/toyProject7/karrot/socialLogin/handler/CustomAuthenticationSuccessHandler.kt
- 이슈 번호: #<이슈 번호를 입력하세요>
---
- 소셜 로그인 성공후 redirect_uri: https://toykarrot.shop/oauth2/redirect로 변경
> 소셜 로그인 성공시 redirect url 업데이트

- src/main/kotlin/com/toyProject7/karrot/article/ArticleException.kt
- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleLikesEntity.kt
- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleLikesRepository.kt
- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleRepository.kt
- src/main/kotlin/com/toyProject7/karrot/article/service/ArticleService.kt
- src/main/kotlin/com/toyProject7/karrot/image/service/ImageService.kt
- 이슈 번호: #35
---
- 이하 동문
1. PESSIMISTIC LOCK 삭제: 얘랑 관련된거 다 뺌.
2. 게시물 관심 취소 문제 해결
3. 게시물 조회수 제대로 반영되도록, 이제 DB가 Count 해서 반영하도록 했음.
---
---
- 없음.
---
- 없음.
> :bug: Article function(like, unlike, get) 진짜 이젠 될거임

- src/main/kotlin/com/toyProject7/karrot/article/persistence/ArticleEntity.kt
- src/main/kotlin/com/toyProject7/karrot/article/service/ArticleService.kt
- src/main/kotlin/com/toyProject7/karrot/feed/persistence/FeedEntity.kt
- src/main/kotlin/com/toyProject7/karrot/feed/service/FeedService.kt
- src/main/kotlin/com/toyProject7/karrot/image/persistence/ImageUrlEntity.kt
- src/main/kotlin/com/toyProject7/karrot/image/service/ImageService.kt
- 이슈 번호: #36
---
- 이미지 엔티티, ArticleEntity, FeedEntity 수정 완료
ImageUrlEntity가 ArticleEntity, FeedEntity와 연결되어 있지 않던 문제 해결
---
---
- 없음.
---
- 없음.
> Image Entity Reference 문제 해결!

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
…equest
- [√] 백엔드: 보안에서 메번 security 체크하는 부분 단순화
---
- 더 이상 authenticatioin token 발급 안함
---
- [√] Linter
- [√] 모든 테스트 통과
- [√] kanban update
> jwtAuthenticationFilter Simplification

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
- 이슈 번호: #<이슈 번호를 입력하세요>
---
- jwtAuthentication이 소셜로그인뿐만아니라 모든 유저에 해당되게 설정
> 소셜로그인 보안 문제 디버깅

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
> 소셜로그인 jwtauthenticationfilter 버그

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
---
- UsernamePasswordAuthenticationFilter에서 authorities가 null인게 문제일수도있을것같아서 모든 유저를 ROLE_USER로 assign.
> authorities 기본값 추가

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
JwtAuthenticationTokenFilter에서 token이 잘 인증되는지를 확인하기 위한 디버깅 로그 추가
> jwtAuthenticationToken 디버깅 추가

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
- src/main/kotlin/com/toyProject7/karrot/user/service/UserService.kt
- src/main/resources/application.yaml
Changed userDetails to use userPrincipal
> Changed userDetails to use userPrincipal

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
- src/main/kotlin/com/toyProject7/karrot/user/service/UserService.kt
- src/main/resources/application.yaml
added authentication.details = WebAuthenticationDetailsSource().buildDetails(request)
> added authentication.details 

- src/main/kotlin/com/toyProject7/karrot/SecurityConfig.kt
jwtAuthenticationFilter, OAuth2LoginAuthenticationFilter 순서 바꿈
> Feat/social login 

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
:pencil: added fallback filter
> :pencil: added fallback filter

- src/main/kotlin/com/toyProject7/karrot/socialLogin/handler/CustomAuthenticationSuccessHandler.kt
CustomAuthenticationSuccessHandler now explicitly creates token
> :pencil: CustomAuthenticationSuccessHandler now explicitly creates token

- src/main/kotlin/com/toyProject7/karrot/security/JwtAuthenticationFilter.kt
- src/main/resources/application.yaml
---
- <added debugger jwtAuthenticationFilter
1. added debugger jwtAuthenticationFilter 디버깅할수있게 application.yaml 설정
> :bug: added debugger

- src/main/resources/application.yaml
---
- Fixed debugger
1. Fixed debugger
> Fixed debugger

- src/main/kotlin/com/toyProject7/karrot/user/AuthUser.kt
- [√] 백엔드: @AuthUser 클라스 수정
---
- 현재까진  default @AuthUser 클라스 수정
1. 현재까지는 default @AuthUser에 맞게 user를 authenticate했는데 이제는 jwtAuthenticationFilter에서 정의한 authentication 과정에 맞게 확인하게 만듦.
---
- [√] Linter
> specified authuser class

- src/main/kotlin/com/toyProject7/karrot/user/AuthUser.kt
- src/main/kotlin/com/toyProject7/karrot/user/controller/UserController.kt
> AuthUser 추가 함수 지움

- src/main/kotlin/com/toyProject7/karrot/user/AuthUser.kt
- src/main/kotlin/com/toyProject7/karrot/user/persistence/NormalUser.kt
- src/main/kotlin/com/toyProject7/karrot/user/persistence/NormalUserRepository.kt
- src/main/kotlin/com/toyProject7/karrot/user/persistence/SocialUser.kt
- src/main/kotlin/com/toyProject7/karrot/user/persistence/UserRepository.kt
- src/main/kotlin/com/toyProject7/karrot/user/service/UserService.kt
- 이슈 번호: #65
---
- NormalUserRepository.kt 삭제
- UserService.kt 수정
1. NormalUserRepository.kt 삭제: 불필요하여 삭제하였음
2. UserService.kt: 1로 인한 수정 및 불필요한 코드 삭제
---
---
- 없음.
---
- 없음.
> User 패키지 최적화

- src/main/kotlin/com/toyProject7/karrot/article/service/ArticleService.kt
- src/main/kotlin/com/toyProject7/karrot/chatRoom/service/ChatRoomService.kt
- src/main/kotlin/com/toyProject7/karrot/manner/service/MannerService.kt
- 이슈 번호: #67
---
- ChatRoomService.kt / MannerService.kt / ArticleService.kt 수정
없음.
---
---
- 없음.
---
- 없음.
> 다른 패키지의 Repository를 직접 접근할 수 없도록 몇몇 서비스 구조 수정

- src/main/kotlin/com/toyProject7/karrot/auction/AuctionException.kt
- src/main/kotlin/com/toyProject7/karrot/auction/service/AuctionService.kt
---
- 경매 종료 1분 미만 남았을 때 가격을 제안해도 갱신이 안되던 문제 해결
- 경매 종료된 후 가격제안 불가능하게 변경
- 경매 시작가의 5% 단위로 상승 가능하게 변경
---
- 경매 시작가가 20으로 나누어 떨어져야 할듯
---
> 경매 기능 수정사항

- src/main/kotlin/com/toyProject7/karrot/auction/service/AuctionService.kt
> 🐛 Fix updatePrice

- src/main/kotlin/com/toyProject7/karrot/socialLogin/handler/CustomAuthenticationSuccessHandler.kt
- src/main/resources/application.yaml
---
- 네이버 소셜로그인 parameter 변경
1. nickname을 받아오려하고있었는데 네이버에서는 profile을 받아오고 여기서 이름을 빼내와야한다. 즉, nickname이라는 scope는 애초에 없다.
---
> :bug: fixed naver login bugs

- src/main/kotlin/com/toyProject7/karrot/profile/service/ProfileService.kt
- src/main/kotlin/com/toyProject7/karrot/user/service/UserService.kt
---
- 프로필 수정에서 닉네임 충돌 체킹 방식 수정
1. **닉네임 충돌 확인**: request.nickname과 user.nickname 비교 과정 추가
---
---
> 🐛 Fix editProfile nickname conflict check

- src/main/kotlin/com/toyProject7/karrot/article/controller/ArticleController.kt
- src/main/kotlin/com/toyProject7/karrot/article/controller/Item.kt
- src/main/kotlin/com/toyProject7/karrot/profile/service/ProfileService.kt
---
- Item에 chatCount: Int 추가
---
> 🔨 Add chatCount in Item

- src/main/kotlin/com/toyProject7/karrot/article/controller/Article.kt
---
- Article에 buyer: User 추가. 없으면 null
> ✏️ Add buyer to Article

- src/main/kotlin/com/toyProject7/karrot/manner/service/MannerService.kt
> 🔨 Rounding temperature
